<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RJ88POF" failures="1" tests="1" name="PositiveLogInTest123" time="30.115" errors="0" timestamp="2020-12-09T02:23:28 IST">
  <testcase classname="com.webapp.loginpagetests.PositiveLogInTests" name="logInTest" time="16.885">
    <failure type="java.lang.AssertionError" message="actualSuccessMessage does not contain expectedSuccessMessage
expectedSuccessMessage: You logged into a secure are!
actualSuccessMessage: You logged into a secure area!
× expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: actualSuccessMessage does not contain expectedSuccessMessage
expectedSuccessMessage: You logged into a secure are!
actualSuccessMessage: You logged into a secure area!
× expected [true] but found [false]
at com.webapp.loginpagetests.PositiveLogInTests.logInTest(PositiveLogInTests.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- logInTest -->
</testsuite> <!-- PositiveLogInTest123 -->
